import { CoursesType, EPriveleges, UsersType, ModulesType } from '@/@types';

export const Cursos: CoursesType[] = [
   {
     id: "1",
     name: "Programação em JavaScript",
     ownerId: "123",
     rating: 4.5,
     numberOfRatings: 20,
     photo: "imagem1.jpg",
     enrollmentsNumber: 100,
     price: 49.99,
   },
   {
     id: "2",
     name: "Design Gráfico",
     ownerId: "456",
     rating: 4.2,
     numberOfRatings: 15,
     photo: "imagem2.jpg",
     enrollmentsNumber: 80,
     price: 39.99,
   },
   {
     id: "3",
     name: "Marketing Digital",
     ownerId: "789",
     rating: 4.7,
     numberOfRatings: 30,
     photo: "imagem3.jpg",
     enrollmentsNumber: 120,
     price: 59.99,
   },
   {
     id: "4",
     name: "Fotografia",
     ownerId: "101",
     rating: 4.4,
     numberOfRatings: 18,
     photo: "imagem4.jpg",
     enrollmentsNumber: 70,
     price: 44.99,
   },
   {
     id: "5",
     name: "Marketing de Mídia Social",
     ownerId: "202",
     rating: 4.6,
     numberOfRatings: 25,
     photo: "imagem5.jpg",
     enrollmentsNumber: 90,
     price: 54.99,
   },
   {
     id: "6",
     name: "Desenvolvimento Web",
     ownerId: "303",
     rating: 4.8,
     numberOfRatings: 35,
     photo: "imagem6.jpg",
     enrollmentsNumber: 150,
     price: 69.99,
   },
   {
     id: "7",
     name: "Inglês Avançado",
     ownerId: "404",
     rating: 4.9,
     numberOfRatings: 40,
     photo: "imagem7.jpg",
     enrollmentsNumber: 200,
     price: 79.99,
   },
   {
     id: "8",
     name: "Ciência de Dados",
     ownerId: "505",
     rating: 4.7,
     numberOfRatings: 32,
     photo: "imagem8.jpg",
     enrollmentsNumber: 130,
     price: 64.99,
   },
   {
     id: "9",
     name: "Culinária Italiana",
     ownerId: "606",
     rating: 4.3,
     numberOfRatings: 17,
     photo: "imagem9.jpg",
     enrollmentsNumber: 60,
     price: 49.99,
   },
   {
     id: "10",
     name: "Yoga e Meditação",
     ownerId: "707",
     rating: 4.6,
     numberOfRatings: 22,
     photo: "imagem10.jpg",
     enrollmentsNumber: 85,
     price: 59.99,
   },
   {
    id: "11",
    name: "Aprendendo React",
    ownerId: "808",
    rating: 4.2,
    numberOfRatings: 19,
    photo: "imagem11.jpg",
    enrollmentsNumber: 85,
    price: 54.99,
  },
  {
    id: "12",
    name: "Ilustração Digital",
    ownerId: "909",
    rating: 4.6,
    numberOfRatings: 24,
    photo: "imagem12.jpg",
    enrollmentsNumber: 95,
    price: 49.99,
  },
  {
    id: "13",
    name: "Programação em Python",
    ownerId: "1010",
    rating: 4.8,
    numberOfRatings: 38,
    photo: "imagem13.jpg",
    enrollmentsNumber: 50,
    price: 69.99,
  },
  {
    id: "14",
    name: "Fotografia de Paisagem",
    ownerId: "1111",
    rating: 4.4,
    numberOfRatings: 21,
    photo: "imagem14.jpg",
    enrollmentsNumber: 72,
    price: 44.99,
  },
  {
    id: "15",
    name: "Gestão de Redes Sociais",
    ownerId: "1212",
    rating: 4.7,
    numberOfRatings: 29,
    photo: "imagem15.jpg",
    enrollmentsNumber: 80,
    price: 59.99,
  },
  {
    id: "16",
    name: "Desenvolvimento Android",
    ownerId: "1313",
    rating: 4.9,
    numberOfRatings: 42,
    photo: "imagem16.jpg",
    enrollmentsNumber: 88,
    price: 79.99,
  },
  {
    id: "17",
    name: "Introdução à Inteligência Artificial",
    ownerId: "1414",
    rating: 4.7,
    numberOfRatings: 33,
    photo: "imagem17.jpg",
    enrollmentsNumber: 140,
    price: 64.99,
  },
  {
    id: "18",
    name: "Culinária Japonesa",
    ownerId: "1515",
    rating: 4.3,
    numberOfRatings: 16,
    photo: "imagem18.jpg",
    enrollmentsNumber: 55,
    price: 49.99,
  },
  {
    id: "19",
    name: "Meditação Guiada",
    ownerId: "1616",
    rating: 4.6,
    numberOfRatings: 23,
    photo: "imagem19.jpg",
    enrollmentsNumber: 88,
    price: 59.99,
  },
  {
    id: "20",
    name: "Espanhol para Iniciantes",
    ownerId: "1717",
    rating: 4.5,
    numberOfRatings: 21,
    photo: "imagem20.jpg",
    enrollmentsNumber: 78,
    price: 39.99,
  },
];


export const Modules: ModulesType[] = [
  {
    id: "1",
    courseId: "curso1",
    teacherId: "professor1",
    name: "Item 1",
    description: "Descrição do Item 1",
  },
  {
    id: "2",
    courseId: "curso2",
    teacherId: "professor2",
    name: "Item 2",
    description: "Descrição do Item 2",
  },
  {
    id: "3",
    courseId: "curso3",
    teacherId: "professor3",
    name: "Item 3",
    description: "Descrição do Item 3",
  },
  {
    id: "4",
    courseId: "curso4",
    teacherId: "professor4",
    name: "Item 4",
    description: "Descrição do Item 4",
  },
  {
    id: "5",
    courseId: "curso5",
    teacherId: "professor5",
    name: "Item 5",
    description: "Descrição do Item 5",
  },
  {
    id: "6",
    courseId: "curso6",
    teacherId: "professor6",
    name: "Item 6",
    description: "Descrição do Item 6",
  },
  {
    id: "7",
    courseId: "curso7",
    teacherId: "professor7",
    name: "Item 7",
    description: "Descrição do Item 7",
  },
  {
    id: "8",
    courseId: "curso8",
    teacherId: "professor8",
    name: "Item 8",
    description: "Descrição do Item 8",
  },
  {
    id: "9",
    courseId: "curso9",
    teacherId: "professor9",
    name: "Item 9",
    description: "Descrição do Item 9",
  },
  {
    id: "10",
    courseId: "curso10",
    teacherId: "professor10",
    name: "Item 10",
    description: "Descrição do Item 10",
  },
  {
    id: "11",
    courseId: "curso11",
    teacherId: "professor11",
    name: "Item 11",
    description: "Descrição do Item 11",
  },
  {
    id: "12",
    courseId: "curso12",
    teacherId: "professor12",
    name: "Item 12",
    description: "Descrição do Item 12",
  },
  {
    id: "13",
    courseId: "curso13",
    teacherId: "professor13",
    name: "Item 13",
    description: "Descrição do Item 13",
  },
  {
    id: "14",
    courseId: "curso14",
    teacherId: "professor14",
    name: "Item 14",
    description: "Descrição do Item 14",
  },
  {
    id: "15",
    courseId: "curso15",
    teacherId: "professor15",
    name: "Item 15",
    description: "Descrição do Item 15",
  },
  {
    id: "16",
    courseId: "curso16",
    teacherId: "professor16",
    name: "Item 16",
    description: "Descrição do Item 16",
  },
  {
    id: "17",
    courseId: "curso17",
    teacherId: "professor17",
    name: "Item 17",
    description: "Descrição do Item 17",
  },
  {
    id: "18",
    courseId: "curso18",
    teacherId: "professor18",
    name: "Item 18",
    description: "Descrição do Item 18",
  },
  {
    id: "19",
    courseId: "curso19",
    teacherId: "professor19",
    name: "Item 19",
    description: "Descrição do Item 19",
  },
  {
    id: "20",
    courseId: "curso20",
    teacherId: "professor20",
    name: "Item 20",
    description: "Descrição do Item 20",
  },
];

export const Users: UsersType[] = [
  {
    id: '1',
    email: 'usuario1@example.com',
    username: 'usuario1',
    password: 'senha1',
    firstName: 'PrimeiroNome1',
    lastName: 'UltimoNome1',
    photo: 'foto1.jpg',
    cpf: '123.456.789-01',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.student,
  },
  {
    id: '2',
    email: 'usuario2@example.com',
    username: 'usuario2',
    password: 'senha2',
    firstName: 'PrimeiroNome2',
    lastName: 'UltimoNome2',
    photo: 'foto2.jpg',
    cpf: '987.654.321-01',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.administrator,
  },
  {
    id: '3',
    email: 'usuario3@example.com',
    username: 'usuario3',
    password: 'senha3',
    firstName: 'PrimeiroNome3',
    lastName: 'UltimoNome3',
    photo: 'foto3.jpg',
    cpf: '111.222.333-01',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.student,
  },
  {
    id: '4',
    email: 'usuario4@example.com',
    username: 'usuario4',
    password: 'senha4',
    firstName: 'PrimeiroNome4',
    lastName: 'UltimoNome4',
    photo: 'foto4.jpg',
    cpf: '444.555.666-01',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.administrator,
  },
  {
    id: '5',
    email: 'usuario5@example.com',
    username: 'usuario5',
    password: 'senha5',
    firstName: 'PrimeiroNome5',
    lastName: 'UltimoNome5',
    photo: 'foto5.jpg',
    cpf: '777.888.999-01',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.student,
  },
  {
    id: '6',
    email: 'usuario6@example.com',
    username: 'usuario6',
    password: 'senha6',
    firstName: 'PrimeiroNome6',
    lastName: 'UltimoNome6',
    photo: 'foto6.jpg',
    cpf: '101.202.303-01',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.administrator,
  },
  {
    id: '7',
    email: 'usuario7@example.com',
    username: 'usuario7',
    password: 'senha7',
    firstName: 'PrimeiroNome7',
    lastName: 'UltimoNome7',
    photo: 'foto7.jpg',
    cpf: '303.202.101-01',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.student,
  },
  {
    id: '8',
    email: 'usuario8@example.com',
    username: 'usuario8',
    password: 'senha8',
    firstName: 'PrimeiroNome8',
    lastName: 'UltimoNome8',
    photo: 'foto8.jpg',
    cpf: '505.404.303-01',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.administrator,
  },
  {
    id: '9',
    email: 'usuario9@example.com',
    username: 'usuario9',
    password: 'senha9',
    firstName: 'PrimeiroNome9',
    lastName: 'UltimoNome9',
    photo: 'foto9.jpg',
    cpf: '707.606.505-01',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.student,
  },
  {
    id: '10',
    email: 'usuario10@example.com',
    username: 'usuario10',
    password: 'senha10',
    firstName: 'PrimeiroNome10',
    lastName: 'UltimoNome10',
    photo: 'foto10.jpg',
    cpf: '909.808.707-01',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.administrator,
  },
  {
    id: '11',
    email: 'usuario11@example.com',
    username: 'usuario11',
    password: 'senha11',
    firstName: 'PrimeiroNome11',
    lastName: 'UltimoNome11',
    photo: 'foto11.jpg',
    cpf: '111.222.333-02',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.student,
  },
  {
    id: '12',
    email: 'usuario12@example.com',
    username: 'usuario12',
    password: 'senha12',
    firstName: 'PrimeiroNome12',
    lastName: 'UltimoNome12',
    photo: 'foto12.jpg',
    cpf: '444.555.666-02',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.administrator,
  },
  {
    id: '13',
    email: 'usuario13@example.com',
    username: 'usuario13',
    password: 'senha13',
    firstName: 'PrimeiroNome13',
    lastName: 'UltimoNome13',
    photo: 'foto13.jpg',
    cpf: '777.888.999-02',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.student,
  },
  {
    id: '14',
    email: 'usuario14@example.com',
    username: 'usuario14',
    password: 'senha14',
    firstName: 'PrimeiroNome14',
    lastName: 'UltimoNome14',
    photo: 'foto14.jpg',
    cpf: '101.202.303-02',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.administrator,
  },
  {
    id: '15',
    email: 'usuario15@example.com',
    username: 'usuario15',
    password: 'senha15',
    firstName: 'PrimeiroNome15',
    lastName: 'UltimoNome15',
    photo: 'foto15.jpg',
    cpf: '303.202.101-02',
    issued: new Date(),
    lastAccess: new Date(),
    privilege: EPriveleges.student,
  }
]
